name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Show User
        shell: cmd
        run: |
          whoami

      - name: Show Python Launcher
        shell: cmd
        run: |
          py -0p