name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Show User
        shell: cmd
        run: |
          whoami

      - name: Check Python
        shell: cmd
        run: |
          py --version

      - name: Check Pip
        shell: cmd
        run: |
          py -m pip --version