name: Automated Transportation System

on:
  schedule:
    - cron: '0 3 * * 4'   # Thursday 06:00 Israel summer time

  workflow_dispatch:

jobs:
  run-script:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Python
        shell: cmd
        run: |
          py --version

      - name: Install Dependencies
        shell: cmd
        run: |
          py -m pip install --upgrade pip
          py -m pip install selenium

      - name: Run Script
        shell: cmd
        run: |
          py main.py