name: Automated Transportation System

on:
  schedule:
    # Every Thursday at 03:00 UTC
    # (06:00 Israel during daylight saving time)
    - cron: '0 3 * * 4'

  workflow_dispatch:

jobs:
  run-script:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Script
        run: python main.py